// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	UserID         pgtype.UUID
	Username       string
	Role           pgtype.Text
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	Email          string
	FullName       string
	HashedPassword string
}
