// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOneUser = `-- name: CreateOneUser :one
INSERT INTO "users" (
  username,
  email,
  full_name,
  role
) VALUES (
$1, $2, $3, $4
) RETURNING user_id, username, role, created_at, updated_at, email, full_name
`

type CreateOneUserParams struct {
	Username string
	Email    string
	FullName string
	Role     pgtype.Text
}

func (q *Queries) CreateOneUser(ctx context.Context, arg CreateOneUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createOneUser,
		arg.Username,
		arg.Email,
		arg.FullName,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.FullName,
	)
	return i, err
}

const getUsersByEmail = `-- name: GetUsersByEmail :one
SELECT user_id, username, role, created_at, updated_at, email, full_name FROM "users" WHERE "email" = $1 LIMIT 1
`

func (q *Queries) GetUsersByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUsersByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.FullName,
	)
	return i, err
}
