// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO "applications" (
  project_id,
  type,
  name
) 
VALUES ($1, $2, $3) RETURNING app_id, project_id, type, name, created_at, updated_at
`

type CreateApplicationParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Type      string      `json:"type"`
	Name      string      `json:"name"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication, arg.ProjectID, arg.Type, arg.Name)
	var i Application
	err := row.Scan(
		&i.AppID,
		&i.ProjectID,
		&i.Type,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createApplicationConfig = `-- name: CreateApplicationConfig :one
INSERT INTO "application_configs" (
  app_id,
  port,
  variables_json
)
VALUES ($1, $2, $3) 
ON CONFLICT (app_id)
DO UPDATE SET 
  port = $2,
  variables_json = $3, 
  updated_at = NOW()
RETURNING app_cfg_id, app_id, variables_json, created_at, updated_at, port
`

type CreateApplicationConfigParams struct {
	AppID         pgtype.UUID `json:"app_id"`
	Port          int32       `json:"port"`
	VariablesJson []byte      `json:"variables_json"`
}

func (q *Queries) CreateApplicationConfig(ctx context.Context, arg CreateApplicationConfigParams) (ApplicationConfig, error) {
	row := q.db.QueryRow(ctx, createApplicationConfig, arg.AppID, arg.Port, arg.VariablesJson)
	var i ApplicationConfig
	err := row.Scan(
		&i.AppCfgID,
		&i.AppID,
		&i.VariablesJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Port,
	)
	return i, err
}

const findOneApplicationWithProjectMember = `-- name: FindOneApplicationWithProjectMember :one
SELECT app.app_id, app.project_id, app.type, app.name, app.created_at, app.updated_at, config.app_cfg_id, config.app_id, config.variables_json, config.created_at, config.updated_at, config.port, "pm".project_id pm_project_id, "pm".role role
FROM 
  "applications" AS "app"
LEFT JOIN 
  "project_members" as "pm" 
    ON 
      "pm".project_id = "app".project_id
      AND
      "pm".user_id = $2
LEFT JOIN
  "application_configs" as "config"
    ON
      "config".app_id = "app".app_id
WHERE 
  "app".app_id = $1
LIMIT 1
`

type FindOneApplicationWithProjectMemberParams struct {
	AppID  pgtype.UUID `json:"app_id"`
	UserID pgtype.UUID `json:"user_id"`
}

type FindOneApplicationWithProjectMemberRow struct {
	AppID             pgtype.UUID       `json:"app_id"`
	ProjectID         pgtype.UUID       `json:"project_id"`
	Type              string            `json:"type"`
	Name              string            `json:"name"`
	CreatedAt         pgtype.Timestamp  `json:"created_at"`
	UpdatedAt         pgtype.Timestamp  `json:"updated_at"`
	ApplicationConfig ApplicationConfig `json:"application_config"`
	PmProjectID       pgtype.UUID       `json:"pm_project_id"`
	Role              pgtype.Text       `json:"role"`
}

func (q *Queries) FindOneApplicationWithProjectMember(ctx context.Context, arg FindOneApplicationWithProjectMemberParams) (FindOneApplicationWithProjectMemberRow, error) {
	row := q.db.QueryRow(ctx, findOneApplicationWithProjectMember, arg.AppID, arg.UserID)
	var i FindOneApplicationWithProjectMemberRow
	err := row.Scan(
		&i.AppID,
		&i.ProjectID,
		&i.Type,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApplicationConfig.AppCfgID,
		&i.ApplicationConfig.AppID,
		&i.ApplicationConfig.VariablesJson,
		&i.ApplicationConfig.CreatedAt,
		&i.ApplicationConfig.UpdatedAt,
		&i.ApplicationConfig.Port,
		&i.PmProjectID,
		&i.Role,
	)
	return i, err
}

const updateOneApplication = `-- name: UpdateOneApplication :one
UPDATE "applications"
SET 
  name = $2,
  updated_at = $3
WHERE 
  app_id = $1
RETURNING app_id, project_id, type, name, created_at, updated_at
`

type UpdateOneApplicationParams struct {
	AppID     pgtype.UUID      `json:"app_id"`
	Name      string           `json:"name"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateOneApplication(ctx context.Context, arg UpdateOneApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateOneApplication, arg.AppID, arg.Name, arg.UpdatedAt)
	var i Application
	err := row.Scan(
		&i.AppID,
		&i.ProjectID,
		&i.Type,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
