// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApplicationDeployment = `-- name: CreateApplicationDeployment :one
INSERT INTO "application_deployments" (
  app_id,
  artifacts_path,
  build_path,
  variables_snapshot_json,
  version_number,
  status,
  storage_service
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING app_dp_id, app_id, artifacts_path, variables_snapshot_json, created_at, updated_at, storage_service, version_number, status, build_path, container_img_name, container_registry
`

type CreateApplicationDeploymentParams struct {
	AppID                 pgtype.UUID `json:"app_id"`
	ArtifactsPath         string      `json:"artifacts_path"`
	BuildPath             string      `json:"build_path"`
	VariablesSnapshotJson []byte      `json:"variables_snapshot_json"`
	VersionNumber         int32       `json:"version_number"`
	Status                int32       `json:"status"`
	StorageService        string      `json:"storage_service"`
}

func (q *Queries) CreateApplicationDeployment(ctx context.Context, arg CreateApplicationDeploymentParams) (ApplicationDeployment, error) {
	row := q.db.QueryRow(ctx, createApplicationDeployment,
		arg.AppID,
		arg.ArtifactsPath,
		arg.BuildPath,
		arg.VariablesSnapshotJson,
		arg.VersionNumber,
		arg.Status,
		arg.StorageService,
	)
	var i ApplicationDeployment
	err := row.Scan(
		&i.AppDpID,
		&i.AppID,
		&i.ArtifactsPath,
		&i.VariablesSnapshotJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StorageService,
		&i.VersionNumber,
		&i.Status,
		&i.BuildPath,
		&i.ContainerImgName,
		&i.ContainerRegistry,
	)
	return i, err
}

const createDeploymentInstance = `-- name: CreateDeploymentInstance :one
INSERT INTO "deployment_instances" (
  app_id,
  deployment_id,
  container_name,
  host_port,
  container_port,
  status
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING instance_id, app_id, deployment_id, container_name, status, host_id, host_port, container_port, created_at, updated_at
`

type CreateDeploymentInstanceParams struct {
	AppID         pgtype.UUID `json:"app_id"`
	DeploymentID  pgtype.UUID `json:"deployment_id"`
	ContainerName string      `json:"container_name"`
	HostPort      int32       `json:"host_port"`
	ContainerPort int32       `json:"container_port"`
	Status        int32       `json:"status"`
}

func (q *Queries) CreateDeploymentInstance(ctx context.Context, arg CreateDeploymentInstanceParams) (DeploymentInstance, error) {
	row := q.db.QueryRow(ctx, createDeploymentInstance,
		arg.AppID,
		arg.DeploymentID,
		arg.ContainerName,
		arg.HostPort,
		arg.ContainerPort,
		arg.Status,
	)
	var i DeploymentInstance
	err := row.Scan(
		&i.InstanceID,
		&i.AppID,
		&i.DeploymentID,
		&i.ContainerName,
		&i.Status,
		&i.HostID,
		&i.HostPort,
		&i.ContainerPort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findCurrentDeployment = `-- name: FindCurrentDeployment :one
SELECT 
  app_dp_id, app_id, artifacts_path, variables_snapshot_json, created_at, updated_at, storage_service, version_number, status, build_path, container_img_name, container_registry 
FROM 
  "application_deployments" AS AD
WHERE 
  AD.app_id = $1
`

func (q *Queries) FindCurrentDeployment(ctx context.Context, appID pgtype.UUID) (ApplicationDeployment, error) {
	row := q.db.QueryRow(ctx, findCurrentDeployment, appID)
	var i ApplicationDeployment
	err := row.Scan(
		&i.AppDpID,
		&i.AppID,
		&i.ArtifactsPath,
		&i.VariablesSnapshotJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StorageService,
		&i.VersionNumber,
		&i.Status,
		&i.BuildPath,
		&i.ContainerImgName,
		&i.ContainerRegistry,
	)
	return i, err
}

const updateDeployment = `-- name: UpdateDeployment :one
UPDATE "application_deployments"
SET
  app_id = $2,
  artifacts_path = $3,
  variables_snapshot_json = $4,
  storage_service = $5,
  version_number = $6,
  status = $7,
  build_path = $8,
  container_img_name = $9,
  container_registry = $10,
  build_path = $11,
  updated_at = NOW()
WHERE app_dp_id = $1
RETURNING app_dp_id, app_id, artifacts_path, variables_snapshot_json, created_at, updated_at, storage_service, version_number, status, build_path, container_img_name, container_registry
`

type UpdateDeploymentParams struct {
	AppDpID               pgtype.UUID `json:"app_dp_id"`
	AppID                 pgtype.UUID `json:"app_id"`
	ArtifactsPath         string      `json:"artifacts_path"`
	VariablesSnapshotJson []byte      `json:"variables_snapshot_json"`
	StorageService        string      `json:"storage_service"`
	VersionNumber         int32       `json:"version_number"`
	Status                int32       `json:"status"`
	BuildPath             string      `json:"build_path"`
	ContainerImgName      string      `json:"container_img_name"`
	ContainerRegistry     string      `json:"container_registry"`
	BuildPath_2           string      `json:"build_path_2"`
}

func (q *Queries) UpdateDeployment(ctx context.Context, arg UpdateDeploymentParams) (ApplicationDeployment, error) {
	row := q.db.QueryRow(ctx, updateDeployment,
		arg.AppDpID,
		arg.AppID,
		arg.ArtifactsPath,
		arg.VariablesSnapshotJson,
		arg.StorageService,
		arg.VersionNumber,
		arg.Status,
		arg.BuildPath,
		arg.ContainerImgName,
		arg.ContainerRegistry,
		arg.BuildPath_2,
	)
	var i ApplicationDeployment
	err := row.Scan(
		&i.AppDpID,
		&i.AppID,
		&i.ArtifactsPath,
		&i.VariablesSnapshotJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StorageService,
		&i.VersionNumber,
		&i.Status,
		&i.BuildPath,
		&i.ContainerImgName,
		&i.ContainerRegistry,
	)
	return i, err
}

const updateDeploymentInstance = `-- name: UpdateDeploymentInstance :one
INSERT INTO "deployment_instances" (
  instance_id,
  app_id,
  deployment_id,
  container_name,
  host_port,
  container_port,
  status
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (instance_id)
DO UPDATE SET 
  app_id = $2,
  deployment_id = $3,
  container_name = $4,
  host_port = $5,
  container_port = $6,
  updated_at = NOW()
RETURNING instance_id, app_id, deployment_id, container_name, status, host_id, host_port, container_port, created_at, updated_at
`

type UpdateDeploymentInstanceParams struct {
	InstanceID    pgtype.UUID `json:"instance_id"`
	AppID         pgtype.UUID `json:"app_id"`
	DeploymentID  pgtype.UUID `json:"deployment_id"`
	ContainerName string      `json:"container_name"`
	HostPort      int32       `json:"host_port"`
	ContainerPort int32       `json:"container_port"`
	Status        int32       `json:"status"`
}

func (q *Queries) UpdateDeploymentInstance(ctx context.Context, arg UpdateDeploymentInstanceParams) (DeploymentInstance, error) {
	row := q.db.QueryRow(ctx, updateDeploymentInstance,
		arg.InstanceID,
		arg.AppID,
		arg.DeploymentID,
		arg.ContainerName,
		arg.HostPort,
		arg.ContainerPort,
		arg.Status,
	)
	var i DeploymentInstance
	err := row.Scan(
		&i.InstanceID,
		&i.AppID,
		&i.DeploymentID,
		&i.ContainerName,
		&i.Status,
		&i.HostID,
		&i.HostPort,
		&i.ContainerPort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeploymentInstanceStatus = `-- name: UpdateDeploymentInstanceStatus :one
UPDATE "deployment_instances"
  SET status = $2
WHERE
  instance_id = $1
RETURNING 
  instance_id, status
`

type UpdateDeploymentInstanceStatusParams struct {
	InstanceID pgtype.UUID `json:"instance_id"`
	Status     int32       `json:"status"`
}

type UpdateDeploymentInstanceStatusRow struct {
	InstanceID pgtype.UUID `json:"instance_id"`
	Status     int32       `json:"status"`
}

func (q *Queries) UpdateDeploymentInstanceStatus(ctx context.Context, arg UpdateDeploymentInstanceStatusParams) (UpdateDeploymentInstanceStatusRow, error) {
	row := q.db.QueryRow(ctx, updateDeploymentInstanceStatus, arg.InstanceID, arg.Status)
	var i UpdateDeploymentInstanceStatusRow
	err := row.Scan(&i.InstanceID, &i.Status)
	return i, err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :one
UPDATE "application_deployments"
SET 
  status = $2,
  updated_at = NOW()
WHERE
  app_dp_id = $1
RETURNING 
  app_dp_id, app_id, artifacts_path, variables_snapshot_json, created_at, updated_at, storage_service, version_number, status, build_path, container_img_name, container_registry
`

type UpdateDeploymentStatusParams struct {
	AppDpID pgtype.UUID `json:"app_dp_id"`
	Status  int32       `json:"status"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) (ApplicationDeployment, error) {
	row := q.db.QueryRow(ctx, updateDeploymentStatus, arg.AppDpID, arg.Status)
	var i ApplicationDeployment
	err := row.Scan(
		&i.AppDpID,
		&i.AppID,
		&i.ArtifactsPath,
		&i.VariablesSnapshotJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StorageService,
		&i.VersionNumber,
		&i.Status,
		&i.BuildPath,
		&i.ContainerImgName,
		&i.ContainerRegistry,
	)
	return i, err
}
