// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	AppID     pgtype.UUID      `json:"app_id"`
	ProjectID pgtype.UUID      `json:"project_id"`
	Type      string           `json:"type"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type ApplicationConfig struct {
	AppCfgID      pgtype.UUID      `json:"app_cfg_id"`
	AppID         pgtype.UUID      `json:"app_id"`
	VariablesJson []byte           `json:"variables_json"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	Port          int32            `json:"port"`
}

type ApplicationDeployment struct {
	AppDpID               pgtype.UUID      `json:"app_dp_id"`
	AppID                 pgtype.UUID      `json:"app_id"`
	ArtifactsPath         string           `json:"artifacts_path"`
	VariablesSnapshotJson []byte           `json:"variables_snapshot_json"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
	StorageService        string           `json:"storage_service"`
	VersionNumber         int32            `json:"version_number"`
	Status                int32            `json:"status"`
	BuildPath             string           `json:"build_path"`
	ContainerImgName      string           `json:"container_img_name"`
	ContainerRegistry     string           `json:"container_registry"`
}

type DeploymentInstance struct {
	InstanceID    pgtype.UUID      `json:"instance_id"`
	AppID         pgtype.UUID      `json:"app_id"`
	DeploymentID  pgtype.UUID      `json:"deployment_id"`
	ContainerName string           `json:"container_name"`
	Status        int32            `json:"status"`
	HostID        pgtype.UUID      `json:"host_id"`
	HostPort      int32            `json:"host_port"`
	ContainerPort int32            `json:"container_port"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type Organization struct {
	OrgID     pgtype.UUID      `json:"org_id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type OrganizationUser struct {
	OrgID     pgtype.UUID      `json:"org_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Role      string           `json:"role"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Project struct {
	ProjectID pgtype.UUID      `json:"project_id"`
	OrgID     pgtype.UUID      `json:"org_id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type ProjectMember struct {
	ProjectID pgtype.UUID      `json:"project_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Role      string           `json:"role"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	UserID         pgtype.UUID      `json:"user_id"`
	Username       string           `json:"username"`
	Role           pgtype.Text      `json:"role"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	Email          string           `json:"email"`
	FullName       string           `json:"full_name"`
	HashedPassword string           `json:"hashed_password"`
}
