// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO "organizations" (name) VALUES ($1) RETURNING org_id, name, created_at, updated_at
`

func (q *Queries) CreateOrganization(ctx context.Context, name string) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, name)
	var i Organization
	err := row.Scan(
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganizationUser = `-- name: CreateOrganizationUser :one
INSERT INTO "organization_users" (org_id, user_id, role) VALUES ($1, $2, $3) RETURNING org_id, user_id, role, created_at
`

type CreateOrganizationUserParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) CreateOrganizationUser(ctx context.Context, arg CreateOrganizationUserParams) (OrganizationUser, error) {
	row := q.db.QueryRow(ctx, createOrganizationUser, arg.OrgID, arg.UserID, arg.Role)
	var i OrganizationUser
	err := row.Scan(
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOneOrganization = `-- name: DeleteOneOrganization :exec
DELETE FROM "organizations" WHERE org_id = $1
`

func (q *Queries) DeleteOneOrganization(ctx context.Context, orgID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOneOrganization, orgID)
	return err
}

const deleteOrganizationUsersByOrgId = `-- name: DeleteOrganizationUsersByOrgId :exec
DELETE FROM "organization_users" WHERE org_id = $1
`

func (q *Queries) DeleteOrganizationUsersByOrgId(ctx context.Context, orgID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganizationUsersByOrgId, orgID)
	return err
}

const findOneOrganizationById = `-- name: FindOneOrganizationById :one
SELECT org.org_id, org.name, org.created_at, org.updated_at
FROM 
  "organization_users" AS "orgus"
LEFT JOIN "organizations" AS "org" ON "orgus".org_id = "org".org_id 
WHERE 
  "org".org_id = $1 AND "orgus".user_id = $2
`

type FindOneOrganizationByIdParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
}

type FindOneOrganizationByIdRow struct {
	OrgID     pgtype.UUID      `json:"org_id"`
	Name      pgtype.Text      `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) FindOneOrganizationById(ctx context.Context, arg FindOneOrganizationByIdParams) (FindOneOrganizationByIdRow, error) {
	row := q.db.QueryRow(ctx, findOneOrganizationById, arg.OrgID, arg.UserID)
	var i FindOneOrganizationByIdRow
	err := row.Scan(
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOneOrganizationByIdAndRole = `-- name: FindOneOrganizationByIdAndRole :one
SELECT org.org_id, org.name, org.created_at, org.updated_at, "orgus".role "role"
FROM 
  "organization_users" AS "orgus"
LEFT JOIN "organizations" AS "org" ON "orgus".org_id = "org".org_id 
WHERE 
  "org".org_id = $1 AND "orgus".user_id = $2
`

type FindOneOrganizationByIdAndRoleParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
}

type FindOneOrganizationByIdAndRoleRow struct {
	OrgID     pgtype.UUID      `json:"org_id"`
	Name      pgtype.Text      `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	Role      string           `json:"role"`
}

func (q *Queries) FindOneOrganizationByIdAndRole(ctx context.Context, arg FindOneOrganizationByIdAndRoleParams) (FindOneOrganizationByIdAndRoleRow, error) {
	row := q.db.QueryRow(ctx, findOneOrganizationByIdAndRole, arg.OrgID, arg.UserID)
	var i FindOneOrganizationByIdAndRoleRow
	err := row.Scan(
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const findOrganizationsForUser = `-- name: FindOrganizationsForUser :many
SELECT 
  "orgus".org_id, "orgus".user_id, "orgus".role,
  "orgus".created_at orgus_created_at,
  "org".name, "org".created_at org_created_at, "org".updated_at org_updated_at
FROM "organization_users" AS orgus
LEFT JOIN 
  "organizations" AS org ON "orgus".org_id = "org".org_id
WHERE
  "orgus".user_id = $1
`

type FindOrganizationsForUserRow struct {
	OrgID          pgtype.UUID      `json:"org_id"`
	UserID         pgtype.UUID      `json:"user_id"`
	Role           string           `json:"role"`
	OrgusCreatedAt pgtype.Timestamp `json:"orgus_created_at"`
	Name           pgtype.Text      `json:"name"`
	OrgCreatedAt   pgtype.Timestamp `json:"org_created_at"`
	OrgUpdatedAt   pgtype.Timestamp `json:"org_updated_at"`
}

func (q *Queries) FindOrganizationsForUser(ctx context.Context, userID pgtype.UUID) ([]FindOrganizationsForUserRow, error) {
	rows, err := q.db.Query(ctx, findOrganizationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindOrganizationsForUserRow
	for rows.Next() {
		var i FindOrganizationsForUserRow
		if err := rows.Scan(
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.OrgusCreatedAt,
			&i.Name,
			&i.OrgCreatedAt,
			&i.OrgUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOneOrganization = `-- name: UpdateOneOrganization :one
UPDATE "organizations" 
SET 
  name = $1, 
  updated_at = $2 
WHERE 
  org_id = $3
RETURNING org_id, name, created_at, updated_at
`

type UpdateOneOrganizationParams struct {
	Name      string           `json:"name"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	OrgID     pgtype.UUID      `json:"org_id"`
}

func (q *Queries) UpdateOneOrganization(ctx context.Context, arg UpdateOneOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOneOrganization, arg.Name, arg.UpdatedAt, arg.OrgID)
	var i Organization
	err := row.Scan(
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
