// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO "projects" (org_id, name) VALUES ($1, $2) RETURNING project_id, org_id, name, created_at, updated_at
`

type CreateProjectParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	Name  string      `json:"name"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.OrgID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectMember = `-- name: CreateProjectMember :one
INSERT INTO "project_members" 
  (project_id, user_id, role) 
VALUES 
  ($1, $2, $3) 
RETURNING project_id, user_id, role, created_at
`

type CreateProjectMemberParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Role      string      `json:"role"`
}

func (q *Queries) CreateProjectMember(ctx context.Context, arg CreateProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, createProjectMember, arg.ProjectID, arg.UserID, arg.Role)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOneProject = `-- name: DeleteOneProject :exec
DELETE FROM "projects" WHERE project_id = $1
`

func (q *Queries) DeleteOneProject(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOneProject, projectID)
	return err
}

const deleteProjectMembersByProjectId = `-- name: DeleteProjectMembersByProjectId :exec
DELETE FROM "project_members" WHERE project_id = $1
`

func (q *Queries) DeleteProjectMembersByProjectId(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectMembersByProjectId, projectID)
	return err
}

const findOneProjectById = `-- name: FindOneProjectById :one
SELECT project.project_id, project.org_id, project.name, project.created_at, project.updated_at
FROM 
  "project_members" AS "project_members"
LEFT JOIN "projects" AS "project" ON "project_members".project_id = "project".project_id 
WHERE 
  "project".project_id = $1 AND "project_members".user_id = $2
`

type FindOneProjectByIdParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

type FindOneProjectByIdRow struct {
	ProjectID pgtype.UUID      `json:"project_id"`
	OrgID     pgtype.UUID      `json:"org_id"`
	Name      pgtype.Text      `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) FindOneProjectById(ctx context.Context, arg FindOneProjectByIdParams) (FindOneProjectByIdRow, error) {
	row := q.db.QueryRow(ctx, findOneProjectById, arg.ProjectID, arg.UserID)
	var i FindOneProjectByIdRow
	err := row.Scan(
		&i.ProjectID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOneProjectByIdAndRole = `-- name: FindOneProjectByIdAndRole :one
SELECT project.project_id, project.org_id, project.name, project.created_at, project.updated_at, "project_members".role "role"
FROM 
  "project_members" AS "project_members"
LEFT JOIN "projects" AS "project" ON "project_members".project_id = "project".project_id 
WHERE 
  "project".project_id = $1 AND "project_members".user_id = $2
`

type FindOneProjectByIdAndRoleParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

type FindOneProjectByIdAndRoleRow struct {
	ProjectID pgtype.UUID      `json:"project_id"`
	OrgID     pgtype.UUID      `json:"org_id"`
	Name      pgtype.Text      `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	Role      string           `json:"role"`
}

func (q *Queries) FindOneProjectByIdAndRole(ctx context.Context, arg FindOneProjectByIdAndRoleParams) (FindOneProjectByIdAndRoleRow, error) {
	row := q.db.QueryRow(ctx, findOneProjectByIdAndRole, arg.ProjectID, arg.UserID)
	var i FindOneProjectByIdAndRoleRow
	err := row.Scan(
		&i.ProjectID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const findProjectsForUser = `-- name: FindProjectsForUser :many
SELECT 
  "project_members".project_id, "project_members".user_id, "project_members".role,
  "project_members".created_at project_members_created_at,
  "project".org_id, "project".name, "project".created_at project_created_at, "project".updated_at project_updated_at
FROM "project_members" AS project_members
LEFT JOIN 
  "projects" AS project ON "project_members".project_id = "project".project_id
WHERE
  "project_members".user_id = $1
`

type FindProjectsForUserRow struct {
	ProjectID               pgtype.UUID      `json:"project_id"`
	UserID                  pgtype.UUID      `json:"user_id"`
	Role                    string           `json:"role"`
	ProjectMembersCreatedAt pgtype.Timestamp `json:"project_members_created_at"`
	OrgID                   pgtype.UUID      `json:"org_id"`
	Name                    pgtype.Text      `json:"name"`
	ProjectCreatedAt        pgtype.Timestamp `json:"project_created_at"`
	ProjectUpdatedAt        pgtype.Timestamp `json:"project_updated_at"`
}

func (q *Queries) FindProjectsForUser(ctx context.Context, userID pgtype.UUID) ([]FindProjectsForUserRow, error) {
	rows, err := q.db.Query(ctx, findProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindProjectsForUserRow
	for rows.Next() {
		var i FindProjectsForUserRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.ProjectMembersCreatedAt,
			&i.OrgID,
			&i.Name,
			&i.ProjectCreatedAt,
			&i.ProjectUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOneProject = `-- name: UpdateOneProject :one
UPDATE "projects" 
SET 
  name = $1, 
  updated_at = $2 
WHERE 
  project_id = $3
RETURNING project_id, org_id, name, created_at, updated_at
`

type UpdateOneProjectParams struct {
	Name      string           `json:"name"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	ProjectID pgtype.UUID      `json:"project_id"`
}

func (q *Queries) UpdateOneProject(ctx context.Context, arg UpdateOneProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateOneProject, arg.Name, arg.UpdatedAt, arg.ProjectID)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
