// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOneUser = `-- name: CreateOneUser :one
INSERT INTO "users" (
  username,
  email,
  full_name,
  hashed_password,
  role
) VALUES (
$1, $2, $3, $4, $5
) RETURNING user_id, username, role, created_at, updated_at, email, full_name, hashed_password
`

type CreateOneUserParams struct {
	Username       string      `json:"username"`
	Email          string      `json:"email"`
	FullName       string      `json:"full_name"`
	HashedPassword string      `json:"hashed_password"`
	Role           pgtype.Text `json:"role"`
}

func (q *Queries) CreateOneUser(ctx context.Context, arg CreateOneUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createOneUser,
		arg.Username,
		arg.Email,
		arg.FullName,
		arg.HashedPassword,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.FullName,
		&i.HashedPassword,
	)
	return i, err
}

const findOneUserByEmail = `-- name: FindOneUserByEmail :one
SELECT user_id, username, role, created_at, updated_at, email, full_name, hashed_password FROM "users" WHERE "email" = $1 LIMIT 1
`

func (q *Queries) FindOneUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findOneUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.FullName,
		&i.HashedPassword,
	)
	return i, err
}

const findOneUserById = `-- name: FindOneUserById :one
SELECT user_id, username, role, created_at, updated_at, email, full_name, hashed_password FROM "users" WHERE "user_id" = $1 LIMIT 1
`

func (q *Queries) FindOneUserById(ctx context.Context, userID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findOneUserById, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.FullName,
		&i.HashedPassword,
	)
	return i, err
}
