package deployment

const (
	APP_TYPE_NODEJS_CONTAINER = "container_nodejs"
)

const (
	DEPLOY_STATUS_INITIATED = 1
	DEPLOY_STATUS_BUILD_EXTRACTED = 2
	DEPLOY_STATUS_BUILD_IMAGE_BUILT = 3
	DEPLOY_STATUS_BUILD_IMAGE_PUSHED = 4
	DEPLOY_STATUS_BUILD_INSTANCE_STARTED = 5
)

const (
	DEPLOY_INSTANCE_STATUS_STOPPED = 0
	DEPLOY_INSTANCE_STATUS_RUNNING = 1
)
